apiVersion: v1
kind: Pod
metadata:
  name: nginx-h
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    resources:
        limits:
          cpu: "0.5"
          memory: "600M"
        softRequests:
          cpu: "0.2"
          memory: "500M"
